#!/usr/bin/env bash

./openshift-router \
 --config ${KUBECONFIG:-$HOME/.kube/config} \
 --template $PWD/images/router/haproxy/conf/haproxy-config.template \
 --reload /usr/bin/true --working-dir /tmp/var/lib/haproxy \
 --v=2
