#!/usr/bin/env bash

set -eu

t="$PWD/haproxy-config.template"
t="$PWD/images/router/haproxy/conf/haproxy-config.template"

cp $t /tmp/lib/haproxy/conf/haproxy-config.template

srcdir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"

pushd /tmp/lib/haproxy/conf

perf record ${srcdir}/openshift-router \
 --config ${KUBECONFIG:-$HOME/.kube/config} \
 --template /tmp/lib/haproxy/conf/haproxy-config.template \
 --reload /usr/bin/true \
 --v=2
