FROM registry.access.redhat.com/ubi8/ubi
RUN rpm -qp --changelog https://github.com/frobware/haproxy-builds/raw/master/rhaos-4.13-rhel-8/haproxy22-2.2.24-5.rhaos4.13.el8.x86_64.rpm | head -n 10
RUN yum install -y https://github.com/frobware/haproxy-builds/raw/master/rhaos-4.13-rhel-8/haproxy22-2.2.24-5.rhaos4.13.el8.x86_64.rpm
RUN INSTALL_PKGS="rsyslog procps-ng util-linux socat" && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all && \
    mkdir -p /var/lib/haproxy/router/{certs,cacerts,whitelists} && \
    mkdir -p /var/lib/haproxy/{conf/.tmp,run,bin,log} && \
    touch /var/lib/haproxy/conf/{{os_http_be,os_edge_reencrypt_be,os_tcp_be,os_sni_passthrough,os_route_http_redirect,cert_config,os_wildcard_domain}.map,haproxy.config} && \
    setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy && \
    chown -R :0 /var/lib/haproxy && \
    chmod -R g+w /var/lib/haproxy

# COPY haproxy /usr/sbin/haproxy
# RUN  chmod 755 /usr/sbin/haproxy
# RUN  setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy

COPY images/router/haproxy/ /var/lib/haproxy/
COPY openshift-router /usr/bin/openshift-router
USER 1001
EXPOSE 80 443 7000
WORKDIR /var/lib/haproxy/conf
ENV XDG_CONFIG_HOME=/tmp \
    TEMPLATE_FILE=/var/lib/haproxy/conf/haproxy-config.template \
    RELOAD_SCRIPT=/var/lib/haproxy/reload-haproxy
ENTRYPOINT ["/usr/bin/openshift-router", "--v=2"]
