apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: router-debug-deployment-rolebinding
  namespace: openshift-ingress
subjects:
- kind: ServiceAccount
  name: router
  namespace: openshift-ingress
roleRef:
  kind: Role
  name: router-deployment-role
  apiGroup: rbac.authorization.k8s.io
