apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: custom-scc
allowHostNetwork: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowedCapabilities:
- ALL
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostPID: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-ingress:router
- system:serviceaccount:openshift-ingress:default
