apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-ingress
  name: deployment-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
